### ISSUE TITLE
Can you add some use cases to describe how to use it to parse dwarf file?

### ISSUE THREAD

**Issue by zhongchengyong** [aykutkilic/bicirik-dwarf#3]
I want to parse a dwarf file,but I don't know how to use this library.

**Comment by DomonkosSuranyi** [comment]
@giticaniup!
Unfortunately @aykutkilic is not an active GitHub member now. I have a fork of this repo (https://github.com/DomonkosSuranyi/bicirik-dwarf/tree/further) where I updated the README.md. Now it explains how to use the bicirik-dwarf API.
If you have further questions you can find me via email.
And please give me a feedback if you have managed to integrate it into your project!

**Comment by zhongchengyong** [comment]
@DomonkosSuranyi Thank you very much.I have read both the source code and your project,your code is helpful to me.Now my problem solved.
